name: Build Flutter Android APK

on:
  push:
    branches:
      - main
    paths:
      - "lib/main.dart"
      - "android/app/build.gradle.kts"
      - "pubspec.yaml"
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build Android APK
        run: |
          flutter pub get
          flutter build apk --release


      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
         appId: ${{ secrets.FIREBASE_APP_ID }}
         token: ${{ secrets.FIREBASE_AUTH_TOKEN }}
         groups: ramya.r@nativewit.in  # or comma-separated email addresses
         file: build/app/outputs/flutter-apk/app-release.apk
