name: Build Flutter iOS App

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "ios/Runner/AppDelegate.swift"
      - "lib/main.dart"
      - "pubspec.yaml"

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install CocoaPods
        working-directory: ios
        run: |
            pod install
#      - name: Save App Store Connect API key to file
#        run: |
#            echo "${{ secrets.APPSTORE_CONNECT_API_KEY_BASE64 }}" | base64 --decode > AuthKey.p8
#      - name: Set up App Store Connect API Key
#        uses: maierj/app-store-connect-api-key@v1
#        id: connectapi
#        with:
#         apiKeyId: ${{ secrets.APPSTORE_CONNECT_API_KEY_ID }}
#         issuerId: ${{ secrets.APPSTORE_CONNECT_API_ISSUER_ID }}
#         privateKey: ${{ secrets.APPSTORE_CONNECT_API_PRIVATE_KEY }}

      - name: Install Apple certificate and provisioning profile
        uses: apple-actions/download-provisioning-profiles@v1
        with:
          bundle-id: ${{ secrets.BUNDLE_ID }}
          app-id: ${{ secrets.APP_ID }}
          profile-type: IOS_APP_STORE
          api-private-key: ${{ secrets.APPSTORE_CONNECT_API_PRIVATE_KEY }}
          api-key-id: ${{ secrets.APPSTORE_CONNECT_API_KEY_ID }}
          issuer-id: ${{ secrets.APPSTORE_CONNECT_API_ISSUER_ID }}

      - name: Install certificates
        uses: apple-actions/import-codesign-certs@v2
        with:
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}
          p12-file-base64: ${{ secrets.DISTRIBUTION_CERT_BASE64 }}
          p12-password: ${{ secrets.P12_PASSWORD }}
    

      - name: Build iOS Archive
        run: |
          flutter pub get
          flutter build ios --release 

      - name: Upload iOS Archive
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/ipa/github_actions.ipa
