name: Build Flutter iOS App

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "ios/Runner/AppDelegate.swift"
      - "lib/main.dart"
      - "pubspec.yaml"

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install CocoaPods
        run: |
          brew install cocoapods --formula

          if [ ! -f ios/Podfile ]; then
          echo "No Podfile found. Running initial Flutter iOS build..."
          flutter build ios --release --no-codesign
          fi

         cd ios
         pod install

      - name: Get Flutter Dependencies
        run: flutter pub get

      - name: Build iOS Archive
        run: |
          flutter pub get
          flutter build ios --release 

      - name: Upload iOS Archive
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/ipa/github_actions.ipa
