name: Build & Deploy Web

on:
  push:
    branches:
      - main


jobs:
  hosting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter (Dart 3.8.1)
        uses: subosito/flutter-action@v2
        with:
          channel: master  # Ensures Dart 3.8.1+

      - name: Check versions
        run: |
          flutter --version
          dart --version

      - name: Build Web
        run: |
          flutter config --enable-web
          flutter pub get
          flutter build web --release

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:my-website-7ebe3
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
